SC27427 Document Customer JWTs
submarine/submarine-js pull request #2
Opened 2022-08-16 00:22 UTC by matoni109

2022-08-16 05:13 UTC, matoni109 commented
@gavinballard not sure how you feel about a table of contents but it would give a more pointed experience to outbound devs.

2022-08-16 23:11 UTC, gavinballard requested changes
Thanks @matoni109! A couple of comments, some of them nitpicky spelling / grammar suggestions.

2022-08-16 23:11 UTC, gavinballard commented on README.md
> +# Table of Contents
I’m down for the addition of a Table of Contents. I’m a bit “meh” on the use of numbered sections because it becomes a bit of a hassle to add new sections and reduces the atomicity of README changes because you need to change sections of the doc unrelated to the actual section you’re changing.

2022-08-16 23:11 UTC, gavinballard commented on README.md
>  The `authentication` initialisation options provides information about the context the client's being initialised in, specifically the authentication information for the currently logged in customer
This needs a slight tweak I think as it’s not really authentication information in the initialisation options any more.

2022-08-16 23:11 UTC, gavinballard commented on README.md
> +`submarine.js` using [Jason Web Tokens (JWTs)](https://jwt.io/) for authenticating client side requests, and returning sensitive customer information via the JWTs encoded `tokens`.
Using -> uses, Jason -> JSON

2022-08-16 23:11 UTC, gavinballard commented on README.md
> +This allows for a secure environment to exchange customer, and shop information flow via the client.
How about just `exchange customer and shop information with the client`?

2022-08-16 23:11 UTC, gavinballard commented on README.md
> +Here's an example of how you can initialised the Submarine client library within a Liquid template in your **Shopify** theme:
initialised -> initialise

2022-08-16 23:11 UTC, gavinballard commented on README.md
> +    <script src="{{ 'submarine.js' | asset_url }}"></script>
Keep the CDN JS reference please - we don’t need people to upload the latest version of `submarine.js` to their theme

2022-08-18 03:54 UTC, matoni109 commented on README.md
> +# Table of Contents
cool, have removed numbers

2022-08-18 03:58 UTC, matoni109 commented on README.md
> +`submarine.js` using [Jason Web Tokens (JWTs)](https://jwt.io/) for authenticating client side requests, and returning sensitive customer information via the JWTs encoded `tokens`.
🤦‍♂️

2022-08-18 04:29 UTC, gavinballard approved these changes

2022-08-18 04:29 UTC, gavinballard commented
Thanks @matoni109!

2022-08-18 06:09 UTC, merged